from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_VERSION_CONFLICT = "TASK_VERSION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    SOURCE_NOT_STABLE = "SOURCE_NOT_STABLE"
    PATH_MAPPING_INVALID = "PATH_MAPPING_INVALID"
    UNSAFE_TORRENT_PATH = "UNSAFE_TORRENT_PATH"
    TORRENT_META_INVALID = "TORRENT_META_INVALID"
    TORRENT_LIMIT_EXCEEDED = "TORRENT_LIMIT_EXCEEDED"
    TORRENT_HYBRID_INCONSISTENT = "TORRENT_HYBRID_INCONSISTENT"
    MAPPING_AMBIGUOUS = "MAPPING_AMBIGUOUS"
    SOURCE_CHANGED = "SOURCE_CHANGED"
    PIECE_MISMATCH = "PIECE_MISMATCH"
    CROSS_DEVICE_LINK = "CROSS_DEVICE_LINK"
    TARGET_CONFLICT = "TARGET_CONFLICT"
    SOURCE_WRITE_RISK = "SOURCE_WRITE_RISK"
    INSUFFICIENT_SPACE = "INSUFFICIENT_SPACE"
    DOWNLOADER_STATE_MISMATCH = "DOWNLOADER_STATE_MISMATCH"
    ROLLBACK_BLOCKED = "ROLLBACK_BLOCKED"


class DomainViolation(ValueError):
    """可安全暴露稳定错误码、但不携带第三方原始响应的领域异常。"""

    def __init__(self, code: ErrorCode, message: str) -> None:
        self.code = code
        super().__init__(message)
