from enum import StrEnum


class OperationStatus(StrEnum):
    INTENT_RECORDED = "INTENT_RECORDED"
    APPLIED = "APPLIED"
    NOOP = "NOOP"
    ROLLBACK_PENDING = "ROLLBACK_PENDING"
    ROLLED_BACK = "ROLLED_BACK"
    RECONCILE_REQUIRED = "RECONCILE_REQUIRED"
    ROLLBACK_BLOCKED = "ROLLBACK_BLOCKED"
